version: 2

sources:
  - name: northwind
    database: northwind
    schema: raw
    tables:
      - name: customers
      - name: orders
      - name: order_details
      - name: products
      - name: suppliers
      - name: categories
      - name: shippers
      - name: employees
      - name: territories
      - name: regions
      - name: employee_territories