version: 2

sources:
  - name: northwind
    database: northwind
    schema: raw
    tables:
      - name: customers
      - name: orders
      - name: order_details
      - name: products
      - name: categories